"""Domain models for media formats, extraction sessions, and download jobs."""

import hashlib
import json
import math
import time
import uuid
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator


def whole_duration_seconds(value: Optional[float]) -> Optional[int]:
    """Convert precise source duration only at an integer API/UI boundary."""
    if value is None:
        return None
    try:
        seconds = float(value)
    except (TypeError, ValueError):
        return None
    if not math.isfinite(seconds) or seconds < 0:
        return None
    return int(round(seconds))


class VideoCodec(str, Enum):
    """Normalized video codec identifiers."""
    H264 = "H.264 / AVC"
    H265 = "H.265 / HEVC"
    VP9 = "VP9"
    AV1 = "AV1"
    OTHER = "Other"
    NONE = "None"  # Audio-only formats


class AudioCodec(str, Enum):
    """Normalized audio codec identifiers."""
    AAC = "AAC"
    OPUS = "Opus"
    MP3 = "MP3"
    VORBIS = "Vorbis"
    FLAC = "FLAC"
    OTHER = "Other"
    NONE = "None"  # Video-only formats


class MatchingStrategy(str, Enum):
    BEST_QUALITY = "best_quality"
    SMALLEST_FILE = "smallest_file"
    PREFER_READY = "prefer_ready"


class DetailStyle(str, Enum):
    RICH = "rich"
    COMPACT = "compact"


class UserSettings(BaseModel):
    user_id: int
    send_mode: str = "document"
    matching_strategy: MatchingStrategy = MatchingStrategy.BEST_QUALITY
    detail_style: DetailStyle = DetailStyle.RICH
    automatic_audio: bool = True


class FavoriteFormatRule(BaseModel):
    """Flexible multi-select preference rule; values remain open-ended strings."""

    rule_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    user_id: int
    name: str = "Favorite rule"
    priority: int = 0
    enabled: bool = True
    codecs: List[str] = Field(default_factory=lambda: ["any"])
    resolutions: List[str] = Field(default_factory=lambda: ["any"])
    fps_values: List[str] = Field(default_factory=lambda: ["best"])
    containers: List[str] = Field(default_factory=lambda: ["any"])

    @field_validator("codecs", "resolutions", "fps_values", "containers", mode="before")
    @classmethod
    def normalize_choices(cls, value: Any) -> List[str]:
        values = value if isinstance(value, list) else [value]
        cleaned = list(dict.fromkeys(str(item).strip().lower() for item in values if str(item).strip()))
        if "any" in cleaned:
            return ["any"]
        return cleaned or ["any"]


class MediaAsset(BaseModel):
    asset_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:10])
    kind: str
    source_url: str
    ext: str = "bin"
    language: Optional[str] = None
    label: Optional[str] = None
    autogenerated: bool = False
    width: Optional[int] = None
    height: Optional[int] = None
    filesize: Optional[int] = None


class MediaItem(BaseModel):
    item_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:10])
    kind: str = "video"
    source_url: str
    webpage_url: Optional[str] = None
    direct_source_url: Optional[str] = None
    parent_collection_url: Optional[str] = None
    collection_entry_index: Optional[int] = None
    collection_entry_id: Optional[str] = None
    title: str = "Media item"
    extractor_id: Optional[str] = None
    source_extractor: Optional[str] = None
    max_height: Optional[int] = None
    formats: List["MediaFormat"] = Field(default_factory=list)
    thumbnail_url: Optional[str] = None
    duration: Optional[float] = None
    analysis_status: str = "ready"
    analysis_error_category: Optional[str] = None


class MediaFormat(BaseModel):
    """Represents a single media format exposed by an extractor."""
    format_id: str = Field(..., description="Exact extractor format ID")
    internal_key: str = Field(default_factory=lambda: uuid.uuid4().hex[:8])

    # Stream types
    is_video: bool = True
    is_audio: bool = False
    is_muxed: bool = False  # Video + Audio combined in single stream
    requires_separate_audio: bool = False

    # Codecs
    vcodec_raw: Optional[str] = None
    vcodec_normalized: VideoCodec = VideoCodec.OTHER
    acodec_raw: Optional[str] = None
    acodec_normalized: AudioCodec = AudioCodec.OTHER

    # Dimensions & Quality
    width: Optional[int] = None
    height: Optional[int] = None
    resolution_label: Optional[str] = None  # e.g., "1080p", "720p"
    fps: Optional[float] = None
    vbr: Optional[float] = None  # Video bitrate kbps
    abr: Optional[float] = None  # Audio bitrate kbps
    tbr: Optional[float] = None  # Total bitrate kbps

    # Container & Protocol
    ext: str = Field(default="mp4", description="File extension / container")
    protocol: Optional[str] = None

    # Audio metadata
    audio_language: Optional[str] = None
    audio_is_default: bool = False
    audio_is_original: bool = False

    # Size handling (Mandatory distinction)
    filesize: Optional[int] = None  # Exact bytes
    filesize_approx: Optional[int] = None  # Approximate bytes
    format_note: Optional[str] = None

    # Raw metadata preservation (additive principle)
    raw_metadata: Dict[str, Any] = Field(default_factory=dict)
    source_identity: Dict[str, Any] = Field(default_factory=dict)

    @property
    def is_exact_size(self) -> bool:
        return self.filesize is not None

    @property
    def effective_size(self) -> Optional[int]:
        return self.filesize if self.filesize is not None else self.filesize_approx

    def format_size_display(self) -> str:
        size = self.effective_size
        if size is None:
            return "Unknown size"
        mb = size / (1024 * 1024)
        if mb >= 1024:
            gb = mb / 1024
            return f"{gb:.2f} GB" if self.is_exact_size else f"~{gb:.2f} GB"
        return f"{mb:.1f} MB" if self.is_exact_size else f"~{mb:.1f} MB"

    def execution_snapshot(self) -> Dict[str, Any]:
        """Return the immutable format identity persisted with a job."""
        data = self.model_dump(mode="json", exclude={"raw_metadata"})
        identity = {
            key: data.get(key)
            for key in (
                "format_id", "vcodec_raw", "vcodec_normalized", "acodec_raw",
                "acodec_normalized", "width", "height", "resolution_label", "fps",
                "ext", "protocol", "is_video", "is_audio", "is_muxed",
                "requires_separate_audio", "audio_language", "audio_is_default",
                "audio_is_original", "filesize", "filesize_approx", "format_note",
                "source_identity",
            )
        }
        identity["fingerprint"] = hashlib.sha256(
            json.dumps(identity, sort_keys=True, separators=(",", ":")).encode("utf-8")
        ).hexdigest()
        return identity


class MediaSession(BaseModel):
    """Holds extracted metadata and format inventory for a user request."""
    session_id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    user_id: int
    url: str
    canonical_url: Optional[str] = None
    extractor: str = "yt-dlp"

    title: str = "Unknown Title"
    duration: Optional[float] = None  # precise source seconds
    uploader: Optional[str] = None
    thumbnail_url: Optional[str] = None
    description: Optional[str] = None
    upload_date: Optional[str] = None
    media_id: Optional[str] = None
    session_kind: str = "single"
    collection_truncated: bool = False
    thumbnails: List[MediaAsset] = Field(default_factory=list)
    subtitles: List[MediaAsset] = Field(default_factory=list)
    items: List[MediaItem] = Field(default_factory=list)
    parent_collection_url: Optional[str] = None
    collection_entry_index: Optional[int] = None
    collection_entry_id: Optional[str] = None
    ytdlp_impersonated: bool = False
    cookie_profile: Optional[str] = None
    collection_depth: int = 0

    # Complete format inventory
    formats: List[MediaFormat] = Field(default_factory=list)

    created_at: float = Field(default_factory=time.time)
    expires_at: float = Field(default_factory=lambda: time.time() + 1800)

    @classmethod
    def with_ttl(cls, *, ttl_seconds: int, **data: Any) -> "MediaSession":
        """Create an interactive session using the configured TTL."""
        created_at = float(data.pop("created_at", time.time()))
        return cls(created_at=created_at, expires_at=created_at + ttl_seconds, **data)

    def is_expired(self) -> bool:
        return time.time() > self.expires_at

    def get_format_by_key(self, internal_key: str) -> Optional[MediaFormat]:
        for fmt in self.formats:
            if fmt.internal_key == internal_key:
                return fmt
        return None

    def get_format_by_id(self, format_id: str) -> Optional[MediaFormat]:
        for fmt in self.formats:
            if fmt.format_id == format_id:
                return fmt
        return None


class JobStatus(str, Enum):
    QUEUED = "queued"
    CLAIMED = "claimed"
    WAITING_RESOURCES = "waiting_resources"
    DOWNLOADING_VIDEO = "downloading_video"
    DOWNLOADING_AUDIO = "downloading_audio"
    MERGING = "merging"
    UPLOADING = "uploading"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class DownloadJob(BaseModel):
    """Represents an active or queued download job."""
    job_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    media_session_id: str
    user_id: int
    chat_id: int
    message_id: Optional[int] = None  # Status message to update

    # Selected formats
    video_format_id: str
    audio_format_id: Optional[str] = None
    video_format_snapshot: Dict[str, Any] = Field(default_factory=dict)
    audio_format_snapshot: Optional[Dict[str, Any]] = None
    source_url: Optional[str] = None
    canonical_url: Optional[str] = None
    extractor: Optional[str] = None

    # Status & Progress
    status: JobStatus = JobStatus.QUEUED
    progress_pct: float = 0.0
    downloaded_bytes: int = 0
    total_bytes: Optional[int] = None
    speed_bytes_sec: float = 0.0
    eta_seconds: Optional[int] = None
    current_stage: str = "Queued"

    # Process tracking (PID for true cancellation)
    process_pid: Optional[int] = None

    # Timestamps & Error
    created_at: float = Field(default_factory=time.time)
    updated_at: float = Field(default_factory=time.time)
    error_message: Optional[str] = None
    error_category: Optional[str] = None

    # Delivery
    send_mode: str = "document"
    output_path: Optional[str] = None
    telegram_file_id: Optional[str] = None
    claimed_at: Optional[float] = None
    media_kind: str = "video"
    output_identity: Optional[str] = None
    collection_entry_index: Optional[int] = None
    collection_entry_id: Optional[str] = None
    ytdlp_impersonated: bool = False
    cookie_profile: Optional[str] = None
    source_media_id: Optional[str] = None
    thumbnail_url: Optional[str] = None
    source_duration: Optional[float] = None
